### ISSUE TITLE
Bar at bottom of screen should be transparent but has black background 

### ISSUE THREAD

**Issue by ArcanjoMan** [webosbrew/youtube-webos#118]
Is there any way to remove the black part shown in the image?
I noticed that today it was normal, but normally it is black when you pull up to see the videos below another played video.
If you can, please just show me, or maybe I did something wrong?
![Imagem do WhatsApp de 2024-01-05 à(s) 14 37 56_4f611492](https://github.com/webosbrew/youtube-webos/assets/36206040/8ce57848-6875-4843-8a3b-689354895fa9)

**Comment by cremor** [comment]
See #113

**Comment by ArcanjoMan** [comment]
> See #113

how do I do that? I can't do it, could you please make a tutorial that would help me a lot to do it here on television.

**Comment by cremor** [comment]
It's not something you can do. The developers of this app have to fix it.

**Comment by throwaway96** [comment]
We don't have the resources to keep up with changes to the YouTube (for TV) site. There are not really any active developers. I've been merging a few PRs here and there, but I don't even use this app. So it's likely that the only way issues like this one will get fixed is if someone who actually uses the app submits a PR.

**Comment by throwaway96** [comment]
@fire332

Anyone who is feeling brave can try [v0.3.2-rc1](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.2-rc1). I have not tested it *at all*.

**Comment by ArcanjoMan** [comment]
> @fire332
> 
> Anyone who is feeling brave can try [v0.3.2-rc1](https://github.com/webosbrew/youtube-webos/releases/tag/v0.3.2-rc1). I have not tested it *at all*.
> 

I did the test here and it is working perfectly, everything is even transparent![IMG20240110110404.jpg](https://github.com/webosbrew/youtube-webos/assets/36206040/8fe5b825-0399-4739-9ae4-139a9072568c)

**Comment by cremor** [comment]
I can also confirm that this is fixed in v0.3.2-rc1, thanks!

**Comment by cremor** [comment]
@throwaway96 Do you plan to release v0.3.2 anytime soon? I think that "normal" users (who don't install the RC manually) should also profit from this fix.

**Comment by throwaway96** [comment]
This should be fixed in 0.3.2.

**Comment by cremor** [comment]
@throwaway96 Something seems to be inconsistent about the fix.

As I've written before, the fixed worked immediately after I installed v0.3.2-rc1. And I never had any problems with that version.

Today I uninstalled the RC and installed v0.3.2 via the webOS Homebrew Channel TV app. With that version this bug was back. I tried this again a few times by uninstalling and installing the app again, both via the TV app and via the Device Manager Windows app. Sometimes the bug is fixed, but a restart of the app has a high chance of bringing it back.

I can see in the commit history that only the version number was changed since the RC. So how can it be that the final version behaves differantly than the RC?

**Comment by ANewDawn** [comment]
Noticed this bug is back with 0.3.2 which was fixed with the RC version previously.

**Comment by cremor** [comment]
I've tried "downgrading" to v0.3.2-rc1 but the bug is back even with that version. It looks like each start of the app has a 50:50 chance of showing the bug.
That was not the case before I tried to update to v0.3.2 final 😢

**Comment by ANewDawn** [comment]
> I've tried "downgrading" to v0.3.2-rc1 but the bug is back even with that version. It looks like each start of the app has a 50:50 chance of showing the bug. That was not the case before I tried to update to v0.3.2 final 😢

It worked for me when I uninstalled the v0.3.2 version and installed the RC using the dev manager.

I uninstalled using the homebrew app if that made difference. Wonder if lg firmware would make difference I'm on webos 23 2023 model.

**Comment by cremor** [comment]
I also uninstalled the final via the Homebrew Channel TV app and installed the RC via the Device Manager Windows app - just like when I updated from v0.3.1 to v0.3.2-rc1 back in January. But back then I never had the bug with the RC version, whereas now both the RC and the final are inconsistent. I don't understand what's happening here.

**Comment by ANewDawn** [comment]
> I also uninstalled the final via the Homebrew Channel TV app and installed the RC via the Device Manager Windows app - just like when I updated from v0.3.1 to v0.3.2-rc1 back in January. But back then I never had the bug with the RC version, whereas now both the RC and the final are inconsistent. I don't understand what's happening here.

Try uninstalling from lg main menu. Try restarting TV also and make sure YouTube is restarted fully. The YouTube splash logo should appear and not just boot into YouTube already.

**Comment by throwaway96** [comment]
There are zero substantive changes between 0.3.2-rc1 and 0.3.2: <https://github.com/webosbrew/youtube-webos/compare/v0.3.2-rc1...v0.3.2>.

Maybe installing the new version caused some WAM cache to be cleared, resulting in newer files being downloaded from YouTube. Regardless, the difference is on the server side. Somebody is probably going to have to dig into the YouTube JS and see what changed.

**Comment by cremor** [comment]
@0xBADEAFFE You initially fixed this issue. Do you have any idea what YouTube could have changed recently?

**Comment by 0xBADEAFFE** [comment]
> @0xBADEAFFE You initially fixed this issue. Do you have any idea what YouTube could have changed recently to break this again?

@cremor Unfortunately, I don't have any ideas yet. But I am looking for a solution.

**Comment by throwaway96** [comment]
Try this build: https://github.com/throwaway96/youtube-webos/releases/tag/v0.3.3-dev1

**Comment by cremor** [comment]
On first glance this version seems to fix the problem, thanks!
I'll keep testing it since the old version was also inconsistent in the beginning. I'll report back if the problem comes back. If you don't hear anything from me in the next few days you can assume that it's consistently fixed 😄

**Comment by cremor** [comment]
I just updated to v0.3.3-dev3 and it also seems to work fine.

The only thing I noticed is that the panel that pops up on the right side during video display (e.g. to show comments) still has a black background. But I don't remember if this was different in the official app.
