### ISSUE TITLE
Bug: Black screen during playback when using the player interface

### ISSUE THREAD

**Issue by Anguszzzzzzz** [webosbrew/youtube-webos#277]
## YTAF information

- YTAF version: 0.3.6

## TV information

- webOS version: 8.4.0
- Firmware version: 13.40.75
- OTAID: HE_DTV_W23O_AFABATAA
- SoC: o22n
- Model: OLED65C3AUA

## Issue description

When watching a video and trying to navigate the video player interface, e.g. pausing, scrubbing, the video screen would become black. The audio of the video would continue to play, and video can be still seen when navigating in the comment section.

This issue was previously fixed a few releases ago. However, it's back for some reason despite me using the latest version and having not updated the app recently.

Previous issues #224 #203

**Comment by CPTstickybombs** [comment]
can confirm its back as of 25 minutes ago, ive just noticed it. on webos 05.30.10 / ytaf 0.3.6

**Comment by the-nexi** [comment]
Can confirm that the issue went back

**Comment by 6ebeng** [comment]
Same here issue here.

Device - 55SM8600PVA

Firmware version: 05.40.61
webOS version: 4.10.0
OTA ID: HE_DTV_W19H_AFADABAA
SoC: m16p3

**Comment by katagiri37** [comment]
Can confirm same issue here.

Weirdly I wasn't able to play any videos at first. It buffers and didn't load. Now its playing but with the above.

**Comment by Gagac44** [comment]
I have the same issue again. In december update (0.3.6) it was fixed, but now it's back again.

**Comment by 6ebeng** [comment]
> Can confirm same issue here.
> 
> Weirdly I wasn't able to play any videos at first. It buffers and didn't load. Now its playing but with the above.

when you come to interface player buttons the video background completely goes black but when back to video it appear again

**Comment by Avelayy** [comment]
Same issue here on webos version:4.50.90

**Comment by Dsilvabr** [comment]
Same here also and many times a day  the app show me the user selection screen, and the shorts still have a black preview tiles.

webOS version: 4.10.0-17
Firmware version: 05.40.45

**Comment by Muhamed1995** [comment]
Same here

**Comment by bebach8** [comment]
Same issue but it also displays account selection screen every time app is opened as described in #263. Please someone, fix this login screen bug too.

**Comment by Dsilvabr** [comment]
My tv upgraded, i needed to reinstall this YouTube now everytime I turn the TV off and on back again I need to login with the qr code and my phone.

**Comment by magenta1337** [comment]
I'm experiencing the same issue. Additionally, I can't pause the video using the "OK" button in the center of the arrow keys; I have to use the "II" (pause) button instead.

**Comment by LanthaNide93** [comment]
Same here, it started not more than a week ago

**Comment by HealingBlock** [comment]
I'm having this problem too. Started this week, but the shorts were blank since i installed this app 2 weeks ago.

**Comment by sukhish** [comment]
Same issue, using LG C1 on latest firmware.

**Comment by itzRealM12C** [comment]
Same issue on lg 32lm6300pla

**Comment by niepiekm** [comment]
Hi, I get the same black screen on my LG UK7550MLA
Firmware: 05.50.15
webOS TV 4.4.2
LGwebOSTV 4.4.84-636.glacier.26

**Comment by Toddman01** [comment]
Started happening just now. Now I gotta figure out how to re-update this crap the last time it happened. 😑
